=== flowcentraltechnologies/flowcentral/flowcentral-configuration/src/main/resources/xsd/4.2.0/flowcentral-module.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="flowcentral-types.xsd"/>
  <!-- Module -->
  <xs:element name="module">
    <xs:complexType>
      <xs:all>
        <xs:element name="applications" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="application" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                  <xs:attribute type="xs:string" name="shortDescription" use="required"/>
                  <xs:attribute type="xs:string" name="longDescription" use="required"/>
                  <xs:attribute type="xs:boolean" name="autoInstall" use="optional"/>
                  <xs:attribute type="xs:string" name="configFile" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sysParameters" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sysParameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="type" use="optional">
			        <xs:simpleType>
			          <xs:restriction base="xs:string">
			            <xs:enumeration value="BOOLEAN"/>
			            <xs:enumeration value="NUMBER"/>
			            <xs:enumeration value="STRING"/>
			            <xs:enumeration value="NAME"/>
			            <xs:enumeration value="CONTACT"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
                  <xs:attribute type="xs:string" name="code" use="required"/>
                  <xs:attribute type="xs:string" name="description" use="required"/>
                  <xs:attribute type="xs:string" name="editor" use="required"/>
                  <xs:attribute type="xs:string" name="defaultVal" use="optional"/>
                  <xs:attribute type="xs:string" name="filter" use="optional"/>
                  <xs:attribute type="xs:boolean" name="control" use="optional"/>
                  <xs:attribute type="xs:boolean" name="editable" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="description" use="required"/>
      <xs:attribute type="xs:string" name="shortCode" use="required"/>
      <xs:attribute type="xs:string" name="label" use="required"/>
      <xs:attribute type="xs:boolean" name="principal" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== flowcentraltechnologies/flowcentral/flowcentral-codegeneration/src/main/resources/config/codegeneration-module.xml
<?xml version="1.0"?>
<!-- Code generation module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation=" https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="codegeneration" description="$m{codegeneration.module}" shortCode="CDN"
	label="$m{codegeneration.label}">
	<!-- applications -->
	<applications>
		<application name="codegeneration"
			shortDescription="$m{codegeneration.short.description}"
			longDescription="$m{codegeneration.long.description}" autoInstall="true"
			configFile="apps/codegeneration-application.xml" />
	</applications>

	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="CDN-0001" defaultVal="com.flowcentraltech.flowcentral"
			description="$m{codegeneration.sysparam.codegenpackagebase}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0002"
			description="$m{codegeneration.sysparam.messagereplacementlist}"
			editor="!ui-textarea" type="STRING" editable="true" />
		<sysParameter code="CDN-0003" defaultVal="false"
			description="$m{codegeneration.sysparam.codegenskippasswordfields}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="CDN-0004"
			description="$m{codegeneration.sysparam.extensionspath}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0005"
			description="$m{codegeneration.sysparam.utilitiespath}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0006"
			description="$m{codegeneration.sysparam.codegenrepository}"
			editor="!ui-select list:$s{remoterepoconfiglist} listKey:$s{name} blankOption:$s{}"
				type="STRING" editable="true" />
		<sysParameter code="CDN-0007" defaultVal="development"
			description="$m{codegeneration.sysparam.codegenbranch}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0008" defaultVal="false"
			description="$m{codegeneration.sysparam.codegentorepository}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />			
		<sysParameter code="CDN-0009"
			description="$m{codegeneration.sysparam.snapshotpath}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0010"
			description="$m{codegeneration.sysparam.snapshotrepository}"
			editor="!ui-select list:$s{remoterepoconfiglist} listKey:$s{name} blankOption:$s{}"
				type="STRING" editable="true" />
		<sysParameter code="CDN-0011" defaultVal="development"
			description="$m{codegeneration.sysparam.snapshotbranch}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0012" defaultVal="false"
			description="$m{codegeneration.sysparam.snapshottorepository}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="CDN-0013"
			description="$m{codegeneration.sysparam.snapshotslocalfolder}"
			editor="!ui-text maxLen:128" type="STRING" editable="true" />
		<sysParameter code="CDN-0014" defaultVal="true"
			description="$m{codegeneration.sysparam.enablesnapshotslocalfolder}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="CDN-0015" defaultVal="true"
			description="$m{codegeneration.sysparam.publishallworkflowoncodegen}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
	</sysParameters>
</module>

=== flowcentraltechnologies/flowcentral/flowcentral-report/src/main/resources/config/report-module.xml
<?xml version="1.0"?>
<!-- Master report module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation=" https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="report" description="$m{report.module}" shortCode="RPT"
	label="$m{report.label}">
	<!-- Applications -->
	<applications>
		<application name="report"
			shortDescription="$m{report.short.description}"
			longDescription="$m{report.long.description}" autoInstall="true"
			configFile="apps/report-application.xml" />
	</applications>
	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="RPT-0001" defaultVal="web/report/templates/"
			description="$m{report.sysparam.reporttemplatepath}" editor="!ui-text size:40"
			type="STRING" editable="true"/>
		<sysParameter code="RPT-0002" defaultVal="web/images/applicationloginbanner.png"
			description="$m{report.sysparam.reportclientlogo}" editor="!ui-text size:40"
			type="STRING" editable="true"/>
		<sysParameter code="RPT-0003" defaultVal="dynamicreportportrait.jrxml"
			description="$m{report.sysparam.dynamicreportportraittemplate}"
			editor="!ui-text size:40" type="STRING" editable="true"/>
		<sysParameter code="RPT-0004" defaultVal="dynamicreportlandscape.jrxml"
			description="$m{report.sysparam.dynamicreportlandscapetemplate}"
			editor="!ui-text size:40" type="STRING" editable="true"/>
		<sysParameter code="RPT-0005" defaultVal="2"
			description="$m{report.sysparam.reportlistingcolumns}"
			editor="!ui-select list:onetotenlist" type="NUMBER" editable="true"/>
	</sysParameters>
</module>

=== flowcentraltechnologies/flowcentral/flowcentral-notification/src/main/resources/config/notification-module.xml
<?xml version="1.0"?>
<!-- Master notification module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="notification" description="$m{notification.module}"
	shortCode="NOT" label="$m{notification.label}">
	<!-- Applications -->
	<applications>
		<application name="notification"
			shortDescription="$m{notification.short.description}"
			longDescription="$m{notification.long.description}" autoInstall="true"
			configFile="apps/notification-application.xml" />
	</applications>

	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="NOT-0001" defaultVal="true"
			description="$m{notification.sysparam.notificationenabled}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" control="true"
			editable="true" />
		<sysParameter code="NOT-0002" defaultVal="15"
			description="$m{notification.sysparam.notificationmaximumtries}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="NOT-0003" defaultVal="1"
			description="$m{notification.sysparam.notificationretryminutes}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="NOT-0004" defaultVal="20"
			description="$m{notification.sysparam.notificationmaxbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="NOT-0005" defaultVal="false"
			description="$m{notification.sysparam.notificationtestmodeenabled}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" control="true"
			editable="true" />
		<sysParameter code="NOT-0006" defaultVal=""
			description="$m{notification.sysparam.notificationtestmodeetoemail}"
			editor="!ui-textarea rows:8" type="STRING" editable="true" />
		<sysParameter code="NOT-0007" defaultVal=""
			description="$m{notification.sysparam.notificationtestmodeeccemail}"
			editor="!ui-textarea" type="STRING" editable="true" />
		<sysParameter code="NOT-0008" defaultVal=""
			description="$m{notification.sysparam.notificationtestmodeebccemail}"
			editor="!ui-textarea" type="STRING" editable="true" />
		<sysParameter code="NOT-0009" defaultVal="true"
			description="$m{notification.sysparam.notificationhtmlemailenabled}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" control="true"
			editable="true" />
	</sysParameters>
</module>

=== flowcentraltechnologies/flowcentral/flowcentral-security/src/main/resources/config/security-module.xml
<?xml version="1.0"?>
<!-- Security module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation=" https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="security" description="$m{security.module}" shortCode="SEC"
	label="$m{security.label}">
	<!-- Applications -->
	<applications>
		<application name="security"
			shortDescription="$m{security.short.description}"
			longDescription="$m{security.long.description}" autoInstall="true"
			configFile="apps/security-application.xml" />
	</applications>
	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="SEC-0001" defaultVal="false"
			description="$m{security.sysparam.enablepasswordhist}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0002" defaultVal="6"
			description="$m{security.sysparam.passwordhistlen}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="SEC-0003" defaultVal="false"
			description="$m{security.sysparam.enablepasswordexpiry}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0004" defaultVal="30"
			description="$m{security.sysparam.passwordexpirydays}"
			editor="!ui-integer precision:3" type="NUMBER" editable="true" />
		<sysParameter code="SEC-0005" defaultVal="true"
			description="$m{security.sysparam.enableaccountlock}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0006" defaultVal="4"
			description="$m{security.sysparam.maxlogintries}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="SEC-0007"
			defaultVal="lowercaseprincipal-passwordgenerator"
			description="$m{security.sysparam.userpasswordgenerator}"
			editor="!ui-select list:passwordgeneratorlist" type="STRING" editable="true" />
		<sysParameter code="SEC-0008" defaultVal="8"
			description="$m{security.sysparam.userpasswordlength}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="SEC-0009" defaultVal="false"
			description="$m{security.sysparam.userpasswordsendemail}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-000A" defaultVal="/application"
			description="$m{security.sysparam.userdefaultapplication}"
			editor="!ui-select list:webapplicationlist" type="STRING" editable="true" />
		<sysParameter code="SEC-000B" defaultVal="false"
			description="$m{security.sysparam.enabletwofactorauthentication}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-000C" defaultVal="false"
			description="$m{security.sysparam.enablesystemwidemultiloginrule}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-000D" defaultVal="false"
			description="$m{security.sysparam.systemwidemultiloginrule}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-000E" defaultVal="/application"
			description="$m{security.sysparam.applicationkey}"
			editor="!ui-text maxLen:48" type="STRING" editable="true" />
		<sysParameter code="SEC-000F" type="CONTACT"
			description="$m{security.sysparam.administratoremail}"
			editor="!ui-text size:40" editable="true" />
		<sysParameter code="SEC-0010" type="NAME" defaultVal="Administrator"
			description="$m{security.sysparam.administratorname}"
			editor="!ui-text size:24" editable="true" />
		<sysParameter code="SEC-0011" defaultVal="false"
			description="$m{security.sysparam.useloginlocale}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0012" defaultVal="false"
			description="$m{security.sysparam.keeploginevents}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0013" defaultVal="false"
			description="$m{security.sysparam.enablethirdpartypasswordauthentication}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0014" defaultVal="false"
			description="$m{security.sysparam.enablepasswordcomplexity}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SEC-0015" defaultVal="false"
			description="$m{security.sysparam.enablebranchselectionmode}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
	</sysParameters>
</module>

=== flowcentraltechnologies/flowcentral/flowcentral-application/src/main/resources/config/application-module.xml
<?xml version="1.0"?>
<!-- Application module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="application" description="$m{application.module}"
	shortCode="APP" label="$m{application.label}">
	<!-- Applications -->
	<applications>
		<application name="application"
			shortDescription="$m{application.short.description}"
			longDescription="$m{application.long.description}" autoInstall="true"
			configFile="apps/application-application.xml" />
	</applications>
	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="APP-0001" defaultVal="/application"
			description="$m{application.sysparam.defaultapplication}"
			editor="!ui-select list:webapplicationlist" type="STRING" />
		<sysParameter code="APP-0002" defaultVal="true"
			description="$m{application.sysparam.formshowalternateactions}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0003" defaultVal="true"
			description="$m{application.sysparam.menusectionwithitemsonly}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0004" defaultVal="studio"
			description="$m{application.sysparam.studioapplicationname}"
			editor="!ui-text" type="NAME" />
		<sysParameter code="APP-0005" defaultVal="true"
			description="$m{application.sysparam.studiomenuenabled}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0006" defaultVal="/applicationstudio"
			description="$m{application.sysparam.studioapplicationpath}"
			editor="!ui-text" type="STRING" editable="true" />
		<sysParameter code="APP-0007" defaultVal="import"
			description="$m{application.sysparam.importapplicationname}"
			editor="!ui-text" type="NAME" />
		<sysParameter code="APP-0008" defaultVal="false"
			description="$m{application.sysparam.tabbedcontent}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0009" defaultVal="true"
			description="$m{application.sysparam.assignapplicationentityoncreate}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-000A" defaultVal="false"
			description="$m{application.sysparam.useformcolorscheme}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-000B" defaultVal="false"
			description="$m{application.sysparam.tableheaderuppercase}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-000C" defaultVal="false"
			description="$m{application.sysparam.tableheadercenter}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-000D" defaultVal="false"
			description="$m{application.sysparam.strictformreviewmode}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-000E" defaultVal="true"
			description="$m{application.sysparam.autosavesuggestions}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-000F" defaultVal="true"
			description="$m{application.sysparam.tableclassicmode}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0010"
			description="$m{application.sysparam.applicationheadertitle}"
			editor="!ui-text" type="STRING" editable="true" />
		<sysParameter code="APP-0011" defaultVal="false"
			description="$m{application.sysparam.sectionlabelindicationonmenu}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0012" defaultVal="false"
			description="$m{application.sysparam.sectionindicationontabs}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0013" defaultVal="false"
			description="$m{application.sysparam.sectionindicationonpage}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0014" defaultVal="true"
			description="$m{application.sysparam.saveheaderformontabaction}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0015" defaultVal="false"
			description="$m{application.sysparam.showbuttonsforfooteraction}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0016" defaultVal="4"
			description="$m{application.sysparam.searchentrycolumns}"
			editor="!ui-integer precision:1" type="NUMBER" editable="true" />
		<sysParameter code="APP-0017" defaultVal="25"
			description="$m{application.sysparam.searchminimumitemsperpage}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="APP-0018" defaultVal="true"
			description="$m{application.sysparam.highlatencyindication}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0019" defaultVal="false"
			description="$m{application.sysparam.showresolvedbaserestriction}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-001A" defaultVal="true"
			description="$m{application.sysparam.searchentryshowconditions}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-001B" defaultVal="true"
			description="$m{application.sysparam.sectorsortonmenu}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-001C" defaultVal="false"
			description="$m{application.sysparam.formsectionclassicmode}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-001D" defaultVal="false"
			description="$m{application.sysparam.sectioncolorindicationonmenu}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-001E" defaultVal="true"
			description="$m{application.sysparam.enablequickreport}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-001F" defaultVal="false"
			description="$m{application.sysparam.enableviewentityinseparatetab}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0020" defaultVal="false"
			description="$m{application.sysparam.showworkitemsonlogin}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0021" defaultVal="false"
			description="$m{application.sysparam.enablestickyworkitemspage}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0022" defaultVal="true"
			description="$m{application.sysparam.enableclassiclinkdecoration}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0023" defaultVal="false"
			description="$m{application.sysparam.enableappletsourceauditing}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0024" defaultVal="true"
			description="$m{application.sysparam.enableparentstateauditing}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0025" defaultVal="false"
			description="$m{application.sysparam.enableopentabinbrowser}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0026" defaultVal="false"
			description="$m{application.sysparam.enabledraftworkflowmultiitemaction}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0027" defaultVal="5"
			description="$m{application.sysparam.messagevisibilitytimeout}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="APP-0028" defaultVal="false"
			description="$m{application.sysparam.enablemultierrormessages}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-0029" defaultVal="false"
			description="$m{application.sysparam.enablehideerrormessagesoninput}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-002A" defaultVal="false"
			description="$m{application.sysparam.globalclientupdatesychronization}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-002B" defaultVal="true"
			description="$m{application.sysparam.entitysearchonsearchinputchange}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="APP-002C" defaultVal="false"
			description="$m{application.sysparam.enablelongform}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
	</sysParameters>
</module>

=== flowcentraltechnologies/flowcentral/flowcentral-workflow/src/main/resources/config/workflow-module.xml
<?xml version="1.0"?>
<!-- Workflow module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation=" https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="workflow" description="$m{workflow.module}" shortCode="WRK"
	label="$m{workflow.label}">
	<!-- Applications -->
	<applications>
		<application name="workflow"
			shortDescription="$m{workflow.short.description}"
			longDescription="$m{workflow.long.description}" autoInstall="true"
			configFile="apps/workflow-application.xml" />
		<application name="workflowDraft"
			shortDescription="$m{workflow.draft.short.description}"
			longDescription="$m{workflow.draft.long.description}" autoInstall="true"
			configFile="apps/workflow-draft-application.xml" />
	</applications>

	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="WF-0001" defaultVal="64"
			description="$m{workflow.sysparam.processingbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="WF-0002" defaultVal="64"
			description="$m{workflow.sysparam.autoloadingbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="WF-0003" defaultVal="true"
			description="$m{workflow.sysparam.enableupdateonreview}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="WF-0004" defaultVal="true"
			description="$m{workflow.sysparam.enableautoloading}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="WF-0005" defaultVal="64"
			description="$m{workflow.sysparam.itemalertbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="WF-0006" defaultVal="196"
			description="$m{workflow.sysparam.itemejectionbatchsize}"
			editor="!ui-integer precision:4" type="NUMBER" editable="true" />
		<sysParameter code="WF-0007" defaultVal="true"
			description="$m{workflow.sysparam.enableexternaluseraction}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
	</sysParameters>
</module>
