=== flowcentraltechnologies/flowcentral/flowcentral-configuration/src/main/resources/xsd/4.2.0/flowcentral-module.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="flowcentral-types.xsd"/>
  <!-- Module -->
  <xs:element name="module">
    <xs:complexType>
      <xs:all>
        <xs:element name="applications" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="application" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                  <xs:attribute type="xs:string" name="shortDescription" use="required"/>
                  <xs:attribute type="xs:string" name="longDescription" use="required"/>
                  <xs:attribute type="xs:boolean" name="autoInstall" use="optional"/>
                  <xs:attribute type="xs:string" name="configFile" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sysParameters" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sysParameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="type" use="optional">
			        <xs:simpleType>
			          <xs:restriction base="xs:string">
			            <xs:enumeration value="BOOLEAN"/>
			            <xs:enumeration value="NUMBER"/>
			            <xs:enumeration value="STRING"/>
			            <xs:enumeration value="NAME"/>
			            <xs:enumeration value="CONTACT"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
                  <xs:attribute type="xs:string" name="code" use="required"/>
                  <xs:attribute type="xs:string" name="description" use="required"/>
                  <xs:attribute type="xs:string" name="editor" use="required"/>
                  <xs:attribute type="xs:string" name="defaultVal" use="optional"/>
                  <xs:attribute type="xs:string" name="filter" use="optional"/>
                  <xs:attribute type="xs:boolean" name="control" use="optional"/>
                  <xs:attribute type="xs:boolean" name="editable" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="description" use="required"/>
      <xs:attribute type="xs:string" name="shortCode" use="required"/>
      <xs:attribute type="xs:string" name="label" use="required"/>
      <xs:attribute type="xs:boolean" name="principal" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== flowcentraltechnologies/flowcentral/flowcentral-system/src/main/resources/config/system-module.xml
<?xml version="1.0"?>
<!-- Master system module configuration -->
<module
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://schema.flowcentralplatform.com/xsd/4.2.0/flowcentral-module.xsd"
	name="system" description="$m{system.module}"
	shortCode="SYS" label="$m{system.label}">
	<!-- applications -->
	<applications>
		<application name="system"
			shortDescription="$m{system.short.description}"
			longDescription="$m{system.long.description}" autoInstall="true"
			configFile="apps/system-application.xml" />
		<application name="import"
			shortDescription="$m{system.import.short.description}"
			longDescription="$m{system.import.long.description}"
			autoInstall="true" configFile="apps/import-application.xml" />
	</applications>

	<!-- Privileges -->

	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="SYS-0001" defaultVal="Client Title"
			description="$m{system.sysparam.clienttitle}"
			editor="!ui-text size:40" editable="true" />
		<sysParameter code="SYS-0002"
			defaultVal="web/images/applicationbanner.png"
			description="$m{system.sysparam.applicationbanner}"
			editor="!ui-text size:48" editable="true" />
		<sysParameter code="SYS-0003" defaultVal="info@tcdng.com"
			description="$m{system.sysparam.systememail}"
			editor="!ui-text size:48" editable="true" />
		<sysParameter code="SYS-0004" defaultVal="true"
			description="$m{system.sysparam.scheduleranabled}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SYS-0005" defaultVal="5"
			description="$m{system.sysparam.schedulertriggerexpiration}"
			editor="!ui-integer precision:2" editable="true" />
		<sysParameter code="SYS-0006" defaultVal="10"
			description="$m{system.sysparam.schedulermaxtrigger}"
			editor="!ui-integer precision:2" editable="true" />
		<sysParameter code="SYS-0007" defaultVal="true"
			description="$m{system.sysparam.descriptivebuttons}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SYS-0008"
			description="$m{system.sysparam.loginpagetitle}"
			editor="!ui-textarea columns:32" editable="false" />
		<sysParameter code="SYS-0009"
			description="$m{system.sysparam.loginpagesubtitle}"
			editor="!ui-textarea columns:32" editable="false" />
		<sysParameter code="SYS-000A" defaultVal="false"
			description="$m{system.sysparam.downloadpathlogging}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SYS-000B" defaultVal="false"
			description="$m{system.sysparam.enableglobalaccountinginput}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SYS-000C"
			description="$m{system.sysparam.actualprimarytenantid}"
			editor="!ui-integer" type="NUMBER" editable="false" />
		<sysParameter code="SYS-000D" defaultVal="false"
			description="$m{system.sysparam.usetenantdateformat}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="SYS-000E"
			description="$m{system.sysparam.systemdateformat}"
			editor="!ui-select list:sysdateformattypelist blankOption:$s{}"
			type="STRING" editable="true" />
		<sysParameter code="SYS-000F"
			description="$m{system.sysparam.systemdatetimeformat}"
			editor="!ui-select list:sysdatetimeformattypelist blankOption:$s{}"
			type="STRING" editable="true" />
		<sysParameter code="SYS-0010" defaultVal="http://localhost:8080"
			description="$m{system.sysparam.applicationbaseurl}"
			editor="!ui-textarea rows:8" editable="true" />
		<sysParameter code="SYS-0011" defaultVal="1440"
			description="$m{system.sysparam.securedlinkexpiration}"
			editor="!ui-integer precision:6" editable="true" />
		<sysParameter code="SYS-0012"
			description="$m{system.sysparam.distributionfolder}"
			editor="!ui-text" editable="true" />
	</sysParameters>
</module>
